### ISSUE TITLE
BinarySerializationFormatter AccessViolationException in x86 projects

### ISSUE THREAD

**Issue by topsterde** [koszeggy/KGySoft.CoreLibraries#10]
The constructor of BinarySerializationFormatter crashes in x86 projects with this exception:
_AccessViolationException
Fatal error. 0xC0000005
   at DynamicEnumComparerInt32`1[[KGySoft.Serialization.Binary.BinarySerializationOptions, KGySoft.CoreLibraries, Version=6.0.1.0, Culture=neutral, PublicKeyToken=b45eba277439ddfe]].ToUInt64(KGySoft.Serialization.Binary.BinarySerializationOptions)_

Add this property to the csproj:
`<PlatformTarget>x86</PlatformTarget>`

Full Example:
[KGySoftX86.zip](https://github.com/koszeggy/KGySoft.CoreLibraries/files/8139221/KGySoftX86.zip)

**Comment by koszeggy** [comment]
Thank you for the report

**Comment by koszeggy** [comment]
Fixed by [this](https://github.com/koszeggy/KGySoft.CoreLibraries/commit/dc8ad5bcea5a934b4ec08a5d3dae6c7a115020eb) commit. I will arrange an extra release soon.

**Comment by topsterde** [comment]
Thank you for the quick fix.

**Comment by koszeggy** [comment]
The fix has been released in [v6.0.2](https://github.com/koszeggy/KGySoft.CoreLibraries/releases/tag/v6.0.2).
